### ISSUE TITLE
-version does not output version number (but x.y.z)

### ISSUE THREAD

**Issue by uggyuggy** [atc0005/safelinks#77]
Hi,

Thank's for sharing this tool.

Seems the `-version`  does not output version number (but x.y.z)

Example with downloaded binary version `v0.2.2`

```
$ usl -version
usl x.y.z (https://github.com/atc0005/usl)
$
```

also tested with `v0.2.3-alpha.1`

**Comment by atc0005** [comment]
@uggyuggy Thanks for reporting this. Will let you know once a new build is out.

**Comment by atc0005** [comment]
> @uggyuggy Thanks for reporting this. Will let you know once a new build is out.

New release:

- https://github.com/atc0005/safelinks/releases/tag/v0.2.3

**Comment by uggyuggy** [comment]
All good now, thank's @atc0005 👍
